# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21bd76c175f705681ac1b5cab334b0566db367456e056ec4e6cc887afac58507921647817d777747232c810fa48a2154f87aa2c0c2af49f02b036f80278c915d

test:
  secret_key_base: 37a0bb0aceef18f068154a54c275e873967fcccbea1190a2b737325919b3f41e0cfaf3339ed28bb79b4ba2f4620fe1fc159fcb4cf0e8100f6426c69ae03f8f44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
